version: '2'
#version: '2'

services:

  haggar:
    image: haggar:latest
    build: ./haggar
    depends_on:
    - graphite
    - grafana
    command: sh -c "sleep 300 && ./haggar -agents=10 -metrics=10000 -carbon=graphite:2003"

  graphite:
    #image: graphiteapp/graphite-statsd:latest
    image: 5ce143ea419c
    ports:
    - 80:80
    - 2003:2003
    - 8125:8125
    volumes:
    - ./storage:/opt/graphite/storage
    environment:
    - COLLECTD=1
    - GRAPHITE_DEBUG=1
    - REDIS_TAGDB=1
    - GOCARBON=1
    - GRAPHITE_CLUSTER_SERVERS="127.0.0.1:8000"

  grafana:
    image: grafana/grafana:6.4.3
    ports:
    - 3000:3000
    volumes:
    - ./grafana.json:/usr/share/grafana/public/dashboards/home.json:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin

  grafana_bootstrap:
    image: haggar:latest
    entrypoint: /bin/sh
    depends_on:
    - grafana
    volumes:
    - ./grafana-bootstrap.sh:/grafana-bootstrap.sh:ro
    command: >
      -c '/grafana-bootstrap.sh'
